apiVersion: v1
kind: Pod
metadata:
  name: py-client
  labels: 
     app: python_client
spec:
  containers:
  - image: 192.168.33.10:5000/py-client
    name: py-client
    ports:
    - containerPort: 8080
      protocol: TCP
  nodeSelector:
    machine: machine3
