apiVersion: v1
kind: ReplicationController
metadata:
  name: njsapp-rc
spec:
  replicas: 3
  selector:
    app: njs
  template:
    metadata:
      labels:
        app: njs
    spec:
      containers:
      - name: njsapp
        image: 192.168.33.10:5000/njsapp:v1
        ports:
        - containerPort: 8080
      nodeSelector:
        machine: machine2
