apiVersion: v1
kind: Pod
metadata:
  name: njsapp-bug
spec:
  containers:
  - image: 192.168.33.10:5000/njsapp-bug
    name: njsapp-bug
    ports:
    - containerPort: 8080
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /
        port: 8080 
      initialDelaySeconds: 15   
