version: "3.9"

services:

  server:
    container_name: python_server
    networks:
      - mynet
    # expose: 
    #   - "6061"
    build:
      context: .
      dockerfile: dockerfile_server

  client:
    container_name: python_client
    networks:
    - mynet
    build:
      context: .
      dockerfile: dockerfile_client
    depends_on: 
      - server


networks: 
  mynet: