# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "base"

  config.vm.define "machine1" do |machine1|
    machine1.vm.box = "ubuntu/bionic64"
    machine1.vm.network "private_network", ip: "192.168.35.20"
    machine1.vm.synced_folder "machine1_data/", "/vagrant_data", create: true
    machine1.vm.provider "virtualbox" do |machine1_vb|
      # Customize the amount of memory on the VM:
      machine1_vb.memory = "1024"
    end 

    # basic 
    machine1.vm.provision :shell, privileged: false, path: "bootstrap_machine1.sh"

  end

end
