version: "3.9"

networks:
  myNet:
    name: myNet
    driver: bridge

services:

  server:
    container_name: python_server
    networks:
      - myNet
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVICE_8080_SERVER: web
    depends_on:
      - etcd
      - registrator

  etcd:
    container_name: etcd
    image: bitnami/etcd:latest
    environment:
      - NAME=ETCD
      - ALLOW_NONE_AUTHENTICATION=yes
      - INITIAL_ADVERTISE_PEER_URLS=etcd:2380
      - LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ADVERTISE_CLIENT_URLS=etcd:2379
      - LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - 2379:2379 # for client requests
      - 2380:2380 # for peer communication
    networks:
      - myNet

  registrator:
    container_name: registrator
    image: gliderlabs/registrator:latest
    command: -retry-attempts=-1 -retry-interval=1000 -internal etcd://etcd:2379
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    networks: 
      - myNet
    depends_on:
      - etcd

  # nginx:
  #   container_name: nginx
  #   image: nginx
  #   volumes:
  #     - ./templates:/etc/nginx.templates
  #   ports:
  #     - 8080:80
  #   environment:
  #     - NGINX_HOST=foobar.com
  #     - NGINX_PORT=80
    
