version: "3.9"

networks:
  myNet:
    name: myNet
    driver: bridge

volumes:
  etcd_data:
    driver: local

services:

  server:
    container_name: python_server-BLUE
    image: assign3_server
    networks:
      - myNet
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - etcd
      - registrator

  etcd:
    container_name: etcd
    image: bitnami/etcd:latest
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_ENABLE_V2=true
    ports:
      - 2379:2379 # for client requests
      - 2380:2380 # for peer communication
    networks:
      - myNet
    volumes:
      - etcd_data:/bitnami/etcd

  registrator:
    container_name: registrator
    image: gliderlabs/registrator:latest
    command: -retry-attempts=-1 -retry-interval=1000 -internal=false etcd://etcd:2379
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    networks: 
      - myNet
    depends_on:
      - etcd

  nginx:
    container_name: nginx
    image: nginx:1.21.3
    networks:
      - myNet
    volumes:
      - ./nginx-conf.d:/etc/nginx/conf.d
    ports:
      - 8080:80
    depends_on:
      - etcd
      - registrator
