# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "base"

  config.vm.define "machine1" do |machine1|
    machine1.vm.box = "ubuntu/bionic64"
    machine1.vm.network "private_network", ip: "192.168.35.20"
    machine1.vm.synced_folder "machine1_data/", "/vagrant_data", create: true
    machine1.vm.provider "virtualbox" do |m1_vb|
      # Customize the amount of memory on the VM:
      m1_vb.memory = "1024"
    end 

    machine1.vm.provision :shell, path: "bootstrap.sh"

  end

  config.vm.define "machine2" do |machine2|
    machine2.vm.box = "ubuntu/bionic64"
    machine2.vm.network "private_network", ip: "192.168.35.21"
    machine2.vm.network "forwarded_port", guest: 80, host: 8080
    machine2.vm.synced_folder "machine2_data/", "/vagrant_data", create: true
    machine2.vm.provider "virtualbox" do |m2_vb|
      # Customize the amount of memory on the VM:
      m2_vb.memory = "1024"
    end 

    machine2.vm.provision :shell, path: "bootstrap.sh"

  end

  config.vm.define "machine3" do |machine3|
    machine3.vm.box = "ubuntu/bionic64"
    machine3.vm.network "private_network", ip: "192.168.35.22"
    machine3.vm.network "forwarded_port", guest: 40, host: 4040
    machine3.vm.synced_folder "machine3_data/", "/vagrant_data", create: true
    machine3.vm.provider "virtualbox" do |m3_vb|
      # Cus3omize the amount of memory on the VM:
      m3_vb.memory = "1024"
    end 

    machine3.vm.provision :shell, path: "bootstrap.sh"

  end

end
