# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "base"

  config.vm.define "machineX" do |machineX|
    machineX.vm.box = "ubuntu/bionic64"
    machineX.vm.network "private_network", ip: "192.168.35.21"
    machineX.vm.network "forwarded_port", guest: 80, host: 8081
    machineX.vm.synced_folder "machineX_data/", "/vagrant_data", create: true
    machineX.vm.provider "virtualbox" do |mX_vb|
      # Customize the amount of memory on the VM:
      mX_vb.memory = "1024"
    end 

    machineX.vm.provision :shell, privileged: false, path: "bootstrap_machineX.sh"

  end

  config.vm.define "adm" do |adm|
    adm.vm.box = "ubuntu/bionic64"
    adm.vm.network "private_network", ip: "192.168.35.20"
    adm.vm.synced_folder "adm_data/", "/vagrant_data", create: true
    adm.vm.provider "virtualbox" do |adm_vb|
      # Customize the amount of memory on the VM:
      adm_vb.memory = "1024"
    end 

    # basic 
    adm.vm.provision :shell, privileged: false, path: "bootstrap_adm.sh"

  end

end
