apiVersion: v1
kind: Pod
metadata:
  name: curl
  labels: 
     app: ubuntucurl
spec:
  containers:
  - image: 192.168.33.10:5000/ubuntucurl
    name: ubuntucurl
  nodeSelector:
    machine: machine3
